/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * `client.store(...)` input. `embedding` and `links` are optional (a
 * memory with no embedding simply isn't recallable by similarity search;
 * no links means no graph edges).
 */
export interface StoreOptions {
  tenantId: string
  /** One of "working" | "episodic" | "semantic" | "procedural". */
  tier: string
  content: string
  embedding?: Array<number>
  metadata: JsonValue
  links?: Array<LinkInput>
}
/** One graph edge from the memory being stored to an existing memory. */
export interface LinkInput {
  targetId: string
  relationship: string
}
/** `client.recall(...)` input. */
export interface RecallOptions {
  tenantId: string
  query: Array<number>
  k: number
}
/** `client.forget(...)` input. */
export interface ForgetOptions {
  tenantId: string
  id: string
}
/**
 * `Client.connect(...)` input. `backend` defaults to `"embedded"`; `path`
 * defaults to `"z3rno.db"` in the current working directory when the
 * embedded backend is used and `path` is omitted.
 */
export interface ConnectOptions {
  /** One of "embedded" | "postgres". Defaults to "embedded". */
  backend?: string
  path?: string
  connectionString?: string
}
export interface MemoryDto {
  id: string
  tenantId: string
  tier: string
  content: string
  metadata: JsonValue
  /** RFC 3339 timestamp. */
  createdAt: string
}
export interface ForgetProofDto {
  auditEventId: string
  hash: string
}
export interface AuditEventDto {
  id: string
  tenantId: string
  /** "store" | "forget". */
  operation: string
  memoryId: string
  /** RFC 3339 timestamp. */
  at: string
  prevHash?: string
  hash: string
}
/**
 * A connected z3rno client. Construct with `Client.connect(...)`, never
 * `new Client()` — connecting the embedded backend is sync but connecting
 * Postgres needs an `await`, so both go through one consistent async
 * factory rather than a sync constructor plus a separate async path.
 */
export declare class Client {
  static connect(options?: ConnectOptions | undefined | null): Promise<Client>
  /**
   * Which tenant-isolation guarantee this client's backend provides:
   * "embedded" or "postgres". No I/O, so this is sync (not a Promise).
   */
  tier(): string
  store(options: StoreOptions): Promise<MemoryDto>
  recall(options: RecallOptions): Promise<Array<MemoryDto>>
  forget(options: ForgetOptions): Promise<ForgetProofDto | null>
  /**
   * Advanced operations namespace — currently just `.audit(tenantId)`,
   * the one advanced operation the engine has. Mirrors the engine's own
   * `MemoryEngine::advanced()` two-tier verb surface.
   */
  get advanced(): Advanced
}
export declare class Advanced {
  /** The tenant's full audit chain, oldest first. */
  audit(tenantId: string): Promise<Array<AuditEventDto>>
}
