services:
  neo4j:
    image: neo4j:5-community
    ports:
      - "7474:7474" # HTTP browser
      - "7687:7687" # bolt
    environment:
      - NEO4J_AUTH=neo4j/spikepassword
      - NEO4J_PLUGINS=[]
    volumes:
      - neo4j-data:/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6334:6334" # gRPC
      - "6333:6333" # HTTP
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  neo4j-data:
  qdrant-data:
